# Generated by Django 4.0.4 on 2022-07-01 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=None)),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('now_price', models.IntegerField()),
                ('old_price', models.IntegerField()),
                ('availibility', models.CharField(choices=[('Y', 'In_Stock'), ('N', 'Not_In_Stock')], max_length=1)),
            ],
        ),
    ]
