# Generated by Django 4.0.4 on 2022-07-01 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicines',
            name='availibility',
            field=models.CharField(choices=[('Y', 'In Stock'), ('N', 'Not In Stock')], max_length=1),
        ),
        migrations.AlterField(
            model_name='medicines',
            name='image',
            field=models.ImageField(upload_to='static/images/products'),
        ),
    ]
