# Generated by Django 4.0.4 on 2022-07-01 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0002_alter_medicines_availibility_alter_medicines_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicines',
            name='availibility',
            field=models.CharField(choices=[('In Stock', 'In Stock'), ('Not In Stock', 'Not In Stock')], max_length=20),
        ),
        migrations.AlterField(
            model_name='medicines',
            name='image',
            field=models.ImageField(upload_to='static/images/products/all_medicine'),
        ),
    ]
