# Generated by Django 4.0.4 on 2022-07-02 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0003_alter_medicines_availibility_alter_medicines_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicines',
            old_name='now_price',
            new_name='new_price',
        ),
        migrations.AlterField(
            model_name='medicines',
            name='image',
            field=models.ImageField(upload_to='images/products/all_medicine'),
        ),
    ]
