# Generated by Django 4.0.4 on 2022-07-04 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0004_rename_now_price_medicines_new_price_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Medicines',
            new_name='Medicine',
        ),
    ]
